version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ~/.cache/composer:/.composer/cache
    env_file:
      - .env
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network
volumes:
  mysql-volume:
networks:
  app-network:
