version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ~/.cache/composer:/.composer/cache
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
